# Generated by Django 4.0 on 2021-12-13 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='djangoClasses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('courseNumber', models.DecimalField(decimal_places=0, default=0, max_digits=10000)),
                ('instructorName', models.CharField(default='', max_length=50)),
                ('duration', models.FloatField(default=0, max_length=50)),
            ],
        ),
    ]
